MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  ROI_HEADS:
    SCORE_THRESH: 0.2
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 1601
    ATTR_NUM_CLASSES: 401
    EMBEDDING_INIT: False
    EMBEDDING_WEIGHT: "datasets/vg/peter_ann/elmo_embedding.h5py"
    HEAD: "ROIBoxAttrHead"
    LOSS: "FastRCNNLossWithAttrComputation"
    PREDICTOR: "FastRCNNAttrPredictor"
DATASETS:
  TRAIN: ("vg_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  CHECKPOINT_PERIOD: 5000
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 8
OUTPUT_DIR: "output_101_attr"
TEST:
  IMS_PER_BATCH: 8
