MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 2001
    ATTR_NUM_CLASSES: 501
    HEAD: "ROIBoxAttrHead"
    LOSS: "FastRCNNLossWithAttrComputation"
    PREDICTOR: "FastRCNNAttrPredictor"
DATASETS:
  TRAIN: ("vg_train",)
  TEST: ("vg_dev",)
SOLVER:
  CHECKPOINT_PERIOD: 500
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 8
OUTPUT_DIR: "output"
TEST:
  IMS_PER_BATCH: 8
